---
title: "THE AGRICULTURE INDUSTRY – FINAL REPORT"
author: "Group Afonso - Antille Emma, Luana Martins Afonso, Sulejman Mustafic"
date: "`r format(Sys.time(), '%d %B, %Y')`"
format:
  html:
    toc: true
    toc-title: Contents
    toc-expand: 1
    toc-location: left
    number-sections: true  
    toc-depth: 2  
    theme: lux  # Choix d'un thème visuel (optionnel)
    css: styles.css  # Fichier CSS pour personnalisation (optionnel)
    page-layout: full
    link-external-icon: true
    link-external-newwindow: true
    fig-width: 12  
    fig-height: 10
---

::: {#shiny-map}
<iframe src="https://ellitna.shinyapps.io/EcosystemMap/" width="100%" height="600px" frameborder="0">

</iframe>
:::

# Competition and Technological Evolution

## Reasons for Selecting the Agriculture Industry

We have chosen the field of agriculture because it is an area that concerns the whole world and on which the world's population depends for its survival.  Agriculture is also important for countries because it has a direct impact on their economy (via employment, GDP and the food industry). In addition, agriculture faces major challenges, such as population growth, resource scarcity and, above all, global warming, which threatens the survival of certain crops, making it more dependent than ever on innovation. There is also a strong demand (from the publica also) for more sustainable practices, and new practices already exist, sometimes even incorporating AI. It is for these reasons that we have chosen it, as it seems an interesting subject to work on.

## Key Competitive Dynamics

Companies in the agriculture industry such as Bayer continue to dominate through innovation that includes for example genetically modified seeds and precision agriculture technologies. Mergers and acquisitions like Bayer-Monsanto promote more advanced biotechnological solutions with increased corporate control over the market. Each of these organizations provide a lot of input and some maintain an advantage through R&D investments, and by scaling their operations on a global scale. Family farms and cooperatives are also important players, particularly in local markets. These players often adopt organic or sustainable farming practices, which are their main competitive advantage. For example, cooperatives can focus on economies of scale by pooling their resources to improve market access, particularly for smallholders.

The market is somewhat fragmented. While global giants like Bayer or Syngenta dominate input markets, the production side remains distributed among millions of small, medium, and large-scale producers. In regions like North America and Europe, large agribusinesses hold significant influence, but in developing countries, smallholder farms and cooperatives still account for a large share of production.

Besides, sustainability matters a lot in the agricultural sector. For example, the European Green Deal includes targets for decreasing pesticide use, which pushes this sector toward sustainability-driven innovation. Consumer demand for sustainability is becoming a competitive game changer. Farmers and agribusinesses that design or harmonize their operations with more environmentally friendly practices (e.g., mitigate pesticide input or integrate organic farming) can adapt to environmental regulation and a change in consumer preference. This enables them to gain competitive advantage. Also, the changing weather patterns and resource limitations (particularly water) are forcing agricultural companies to adopt climate-resilient technologies and crops. This is both a challenge and an opportunity, with companies that adapt better, like Syngenta (which focuses on drought-resistant seeds), gaining a competitive edge.

Lastly, rising input costs and labor shortages have been challenges to farm profitability, but both challenges are forcing the farming industry to evolve rapidly with automation and precision agriculture technologies becoming economically viable. For example, fields planted with John Deere automated machinery save money on fertilizer and herbicides due to the use of sensor-based precision application systems.

## Technological Trends

In terms of technological trends, we can see a lot of progress in the last few years in the agriculture industry.

-   **Precision agriculture**: images, drones and sensors to process data in real time, enabling farmers to monitor plant health, manage water use efficiently and apply fertilizer with greater precision.

-   **Automation and robotics**: robotics are increasingly used in harvesting, weeding and planting. They help to increase efficiency and reduce labor costs, and even reduce the risk of human error by allowing continuous working.

-   **AI**: they are becoming the main tools for optimizing farming operations. Using AI to oversee big data makes it easier to examine huge datasets, such as soil samples to gain insights into crop management, water saving and predicting the optimum planting period and so helping with reducing environmental impact.

# Sustainable Innovation

## Sustainability Challenges

Agricultural sustainable challenges stem largely from reliance on natural resources and vulnerability to climate change. Few of the major challenges are the following:

### Water Scarcity

One of the greatest threats to sustainable agriculture is water. Agriculture is the biggest user of freshwater, accounting for 70% of total global water withdrawals. Climate change has exacerbated the problem of water scarcity and turned it into a potential looming disaster for regions like California, India and parts of Africa and the Middle East. In particular, water-intensive crops like tree nuts and groundnuts, which locally intensify blue water stress up to 63% of the nut production under severely stressed conditions. For this, farmers should resort to water-efficient irrigation like drip irrigation and adopt technology for recycling of wastewater.

### Greenhouse Gas Emissions

Agricultural emissions contribute to over 12% of global Green Gas emissions, mainly from methane emissions from livestock and nitrous oxide coming from fertilizers. Fertilizers are key for soil fertility but contribute a lot of greenhouse gases while conventional farming (i.e., monocropping) often further exacerbates it. One of agriculture's biggest sustainability challenges is the desire to mitigate these emissions without compromising agricultural productivity.

### Soil Degradation

When large amount of chemical fertilizers is used, and with the land management not done in a sustainable way, like the lack of crop rotation practices, this behavior ends up to degradation of soil fertility in the long-term. Extensive degradation occurs due to over-tilling and monocropping through soil erosion, loss of fertility and compaction. Therefore, agriculture is under threat due to soil degradation, which if left unaddressed can have severe consequences for future food production and hence global food security. Today “33% of the Earth's soils are already degraded and over 90% could become degraded by 2050” (FAO and ITPS, 2015; IPBES, 2018).

### Biodiversity Loss

The expansion of agriculture can destroy habitats leading to a loss in wildlife biodiversity. The situation was made even worse by the extensive use of chemical pesticides and fertilizers that are extremely toxic to many other non-target organisms, including some possible main pollinators. As monocropping reduces biodiversity it also leads to a decrease in the resilience of an ecosystem. This problem can be overcome through agroecology, regenerative agriculture and integrated pest management practices. According to the Food System Impacts on Biodiversity Loss report (2021), “Our global food system is the primary driver of biodiversity loss, with agriculture alone being the identified threat to 24,000 of the 28,000 (86%) species at risk of extinction”

## Sustainability Opportunities:

### Precision Agriculture

Precision agriculture is one of the most promising innovations in agricultural industry, which adjusts resource utilization with technologies like GPS, sensors, drones, and data analytics to maximize efficiency. An example is IoT-enabled sensors. They help reduce waste by monitoring soil moisture and nutrient levels, as a result enabling farmers to apply fertilizers or water only, when necessary, in specific areas, contributing to improved crop yields and lower environmental impact. Globally, 9.8 gigatons of CO2e emissions could be reduced over the course of 2020-2050 through precision farming and by year end in 2030 this sector will have saved farmers US\$40 to \$100 billion annually on input costs.

### Agroecology and Regenerative Agriculture

Agroecological farming includes sustainable ways of production and reflects, for example, different forms of crop rotation, polyculture or biological pest control. Soil health is a new way to address this problem and better the planet. In fact, practices like reduced tillage, cover cropping and composting are promoted. These practices regenerate overexploited land while developing healthier, carbon-rich soil, two of the most effective tools in combating climate change and biodiversity loss.

### Circular Nutrient Management

Circular farming models emphasize nutrient recycling in order to minimize the loss of nutrients that contribute polluting runoff into water bodies, decreasing reliance on synthetic fertilizers. This would close the nutrient loop by taking back more of the organic waste (manure, crop residues…), hence increasing soil fertility. In regions like British Columbia, work is being done to increase nutrient circularity by decreasing synthetic fertilizer imports and broadening the reusing of organic material.

### Water-Saving Technologies

Ways to fight the issues of water shortages are going forward; it is very important to have new technologies in every kind of conservation including drip irrigation, micro-sprinklers and reuse systems. The net effect of these systems is significantly less water used in crop irrigation by the farmers. Precision irrigation systems, on the other hand, can reduce water use by up to 50% compared to traditional methods of irrigation. In McLaren Vale, for example, farmers have been able to reduce their need for fresh water by repurposing treated wastewater from the region to irrigate vineyards.

## Examples of Sustainable Innovations

1.  **EcoRobotix’s Solar-Powered Weeders**: The Swiss-based AgTech company, EcoRobotix has built fully autonomous solar-powered weeding robots to eliminate weeds efficiently. The robots achieve more than 90% reduction in herbicide use by AI alone, what protects the surrounding biodiversity from chemical runoff. This not only reduces input costs for farmers, but it also makes agricultural practices more sustainable by limiting reliance on chemical herbicides

2.  **McLaren Vale Water Recycling Scheme**: Utilization of recycled water for agriculture in the McLaren Vale wine region powers vineyard irrigation with treated wastewater. This represented a massive reduction in the reliance on freshwaters for agriculture in the region, thanks to this innovation. It provides a model that has the potential to be applied in other areas across Australia and even worldwide including possibly parts of Africa, India or Mexico with similar climate conditions (but high-water scarcity) which would deliver novel solutions for sustainable agricultural irrigation on a global scale.

3.  **Syngenta’s Drought-Resistant Seeds**: Syngenta has been at the forefront of developing genetically modified drought-resistant crops. Farmers due to water scarce situation count on drought resistance seeds which have become a key tool in adaptation of climate change. In areas of intense water shortage that threatens agricultural productivity, these crops can really improve yields.

4.  **John Deere’s Precision Farming Equipment**: John Deere drones to support IoT enabled autonomous tractors and precision farming equipment monitoring crop health and controlling inputs very precisely. They encourage smart farming through waste reduction, pollution mitigation and yield improvement making what could be sustainable agricultural practices. In addition, the company is working on AI and big data analytics to assist farm generals in providing predictions concurrently for real-time decision-making by farmers so that efficiency can be enhanced.

5.  **Virtual Fencing for Livestock**: Virtual fencing is a type of pasture management for livestock which, instead of using physical fencing, relies on global positioning systems (GPS) and movement sensors. This technology is supposed to ensure the sustainability of pastures by reducing overgrazing and improving animal welfare. In addition, virtual fencing reduces labor and material costs and adds data-driven information to improve livestock productivity. However, this practice is prohibited in Switzerland, in fact according to the confederation, even though the cows quickly learned the system without longer-term negative effects on animal welfare, Switzerland prohibits this due to animal welfare concerns including negative stress for the animals. But even on the Swiss side, the results are promising after ‘just’ 8 electrical discharges, the cows were able to adapt to the virtual fence. Over the days, the number of discharges fell to very few, or even zero. Another solution is to use sound effects, which is what the company Nofence does.

# Timing of Entry

## Timeline of the Agriculture Industry

# #IMAGE

## The tractor case

As we can see on the timeline, the agricultural industry spans thousands of years, and there are also players in vastly different fields, such as pharmaceuticals, engineering and, quite simply, agriculture itself. So, in order to be able to carry out this work on the timing of strategies, we have no choice this time but to focus on one topic, because there have been hundreds and hundreds of key players and first movers in the history of agriculture. We have decided to focus on the tractor market.

**Ford**’s Fordson and **John Deere**’s Waterloo Boy tractor were the first movers in the early tractor market. A fundamental changing moment in the mechanization of agriculture occurred in 1917 with the introduction of  

# #IMAGES

The Fordson, bringing an affordable and large-scale produced tractor. At the time, **John Deere** also entered the market when he bought Waterloo Gasoline Engine Company in 1918 and introduced its Waterloo Boy. These two firms established the building blocks of rapid acceptance and utilization by farmers in the United States, and ultimately around the world.

Fordson’s Timing Strategy was mass production. Using the techniques of mass production, **Ford** was able to change the way that tractors were manufactured. This meant prospects were able to buy Fordson tractors at a fairly low price, which was particularly important as farm mechanization became necessary for the average farmer due to labor shortages during World War I.

Fordson soon had 75% of the tractor market in the U.S. by the early 1920s just a few years after it was introduced. However, by 1928, Ford temporarily withdrew from the U.S. tractor market, stopping production of the Fordson tractors domestically due to increased competition and shifting focus to cars. Production continued in Europe, where Fordson maintained a presence. The temporary gap left by **Ford**'s withdrawal created opportunities for other companies to expand their market share.

The early success of Waterloo Boy tractors untied Deere from having to start production of a tractor from scratch. Whereas **Ford** chose not to update and improve the design of his original tractor, **Deere** continued to innovate with autonomous tactors and precision farming and improve the Waterloo Boy by developing more powerful and efficient models. Their approach of providing powerful, reliable tractors helped them to survive the turbulent early years of the market and be a dominant player in the market in the long-term. Thus, **John Deere** due to its investments in technological advancements and market penetration is the only major first mover still dominating the tractor market.

In terms of impact of timing on success, Fordson (first mover) held dominance early in the market. But  their focus change allowed fast followers like John **Deere** to later overtake them. **Deere** soundly beat its competitors by the 1960s and became the market leader. First meant that **Deere** had the brand and customer loyalty to claim a leadership position for quality and innovation in agriculture. Having been one of the "first movers" in digital agriculture, like through precision farming with JDLink, it made sure that they defined what standards everyone else had to comply with.

Although **Ford** and **Deere** were the pioneers in this set, fast followers **like International Harvester** (**IHC**) and **Allis-Chalmers** were instrumental to how markets evolved by learning from early entrant successes and failures.

In 1925, the Farmall was introduced **by International Harvester** (**IHC**) as the first general-purpose tractor for row crop cultivation and traditional plowing. The Farmall fit into a crucial niche left by the earlier Fordson tractors, which could not be used on row crops such as corn or cotton. **IHC** was also the first company to offer a power take-off in 1922, enabling tractors power implements like mowers and combines with their engine. As farmers demanded more versatile machinery, this innovation helped **IHC** to again position themselves strongly in the market.

The **IHC** strategy was built around filling in the gaps on Fordson tractors, included more ground clearance for row crops and added versatility to their machines across all types of farming applications. **IHC** also benefited by waiting until the market for stronger tractors existed, then selling into that demand with better designs than those of first movers.

Another important company from this period, **Allis-Chalmers** made the transition from steel to rubber tires in the 1930s. This kind of innovation led to a dramatic increase in efficiency and field speed, providing customers with an attractive edge over competitors. Large farm operations used them because they were one of the first to be offered with diesel engines, which could deliver better fuel economy and low operational costs.

In terms of impact of timing on success, the tractors from the Farmall series of **International Harvester** not only became iconic but also dominated the U.S. market for several decades. Upon introducing the market's first row-crop tractor, designed for row crop farming, **IHC** captured a large portion of the market that Fordson and Waterloo Boy were not able to properly serve. On the other side, **Allis-Chalmers** created a niche market with its rubber tires and diesel engines innovations. Indeed, we can see that both companies, **IHC** and **Allis-Chalmers**, came into the market and were very successful by playing second or third, allowing them to learn from the mistakes of early entrants, identify emerging needs for farmers, and design solutions that would address these issues. However, **IHC** has faded away and merged with **Case Corporation** in 1984 to form the brand seen today as Case **IH**, under **CNH** **Industrial**. This shift highlights that although **IHC** was initially one of the leaders, it could not maintain independence in the evolving market. Regarding **Allis-Chalmers** in the 1980s and 1990s, a series of divestitures transformed and dissolved the firm. **Allis-Chalmers Energy** and **AGCO** are its successors.

Then, **Kubota** and **AGCO**, the late movers, joined the competitive tractor market in the latter half of the 20^th^ century, focusing on specific farming needs and international markets with smaller tractors.

**Kubota** came to the global stage during the 1970s, specializing in small and light tractors particularly those for the sub-40 HP segment. **Kubota** took part in the small farms and hobby farming trend and the increasing demand for tractors in developing countries where smaller tractors were more practical, which make **Kubota** capitalize a lot. It started to integrate technological offerings, such as GPS systems and smart farming solutions, much earlier than any competitor, making **Kubota** the most advanced player and leader across different global geographies in the compact tractor market, especially in Asia and Europe.

**AGCO** entered the market in 1990 with some key acquisitions like **Massey Ferguson** and **Fendt**. **AGCO** took an approach of acquiring traditional brands and deep-rooted distribution channels to grow. **ACGO** was able to buy up and update long-time legacy brands, allowing them to become a significant player in sustainable farming in Europe. Today, **AGCO** has entered the fields of precision farming and smart tractors that are important for contemporary data-driven agriculture.

In terms of impact of timing on success, **Kubota** focused solely on compact tractors and emerging markets, eventually becoming one of the largest global players in that sector. Later entry and focusing on smaller, neglected segments assured **Kubota** to avoid direct competition from giants like **Deere** or **IHC**. However, **Kubota**’s strategy also had limitations, they were not able to compete with **Deere**’s market leadership. **AGCO**'s acquisition-based growth was enabled by the retention of strong brand loyalty and well-established dealer networks. These late entrants prove that if you get the timing right and a focused strategy, there is still room to dominate even in a market filled with established incumbents.

To conclude, timing strategies have proven in the tractor market to not necessarily determine success. First movers lead to initial brand leadership and market power as we can see with **John Deere** or **Ford**. Nevertheless, staying in that position is another matter, and it requires constant innovation to keep up with long-term success as **John Deere**. On the other side, Fordson did not stick around in the tractor market and showed that first-mover advantage can be lost when a new company change focus or fails to keep up with technological change. **Ford** had returned to the market with innovative models such as the 9N and the takeover of **New Holland**, proving that its initial dominance could be regained through strategic partnerships and technological advances. However, its initial inability to innovate and its focus on cars cost it its long-term leadership position in the tractor sector and it was forced to abandon the brand in profit of **CNH** in the 1990s. The Success has followed for companies that have gone down the fast-follow path, such as **IHC** **and Allis-Chalmers**, which quickly adopted the innovations of first movers. These provided an opportunity for fast followers to enter the market at a lower cost and with more reliable technology, which made them win significant market share without shouldering pioneering costs. Lastly, late entrants like **Kubota** and **AGCO**, timed their entry into established or niche markets to not compete head-on with market leaders. Even if they cannot compete for the same market upside, what made them successful is using proven technology and systems to address real farmers’ needs.

# Innovation and Experimentation

<div>

<iframe src="https://ellitna.shinyapps.io/InnovationHubsMap/" width="100%" height="600px" frameborder="0">

</iframe>

</div>

## Innovation Hubs and Key Experimentation centers

There are many innovation hubs and key experimentation centers in the agriculture area. 

FAO Global Network of Digital Agriculture Innovation Hubs, for example, is a network that has been started by the FAO (Food and Agriculture Organization of the United Nations) to promote digital agriculture with hubs in Dominica; Grenada, Ethiopia and Morocco. These hubs will catalyze local digital maturity, partner capacity and national priorities. Their contribution is to support marginalised small-holder farmers, youth and women through the mainstreaming of innovations with digital tools / practices to increase productivity; manage climate risks; enhance inclusive sustainability.

DIH AGRIFOOD in Slovenia Provides one-stop-shop in Slovenia and the EU for digital-based agricultural services including smart farming techs and innovation transfer to achieve sustainable production of high-quality food, contributes by offering support in awareness creation, technology transfer, business model development and Living Lab environment.

SmartAgriHubs, EU-Wide Project, has for objective, digitizing EU agriculture with a €20 million fund under Horizon 2020 by linking nine regional clusters and 2000 competence centers through 140 digital innovation hubs along the value chain. Their goal is to create a fourth industrial revolution in agriculture by bringing 80 digital market solutions and digitizing over two million farms by connecting end-users directly with technology providers.

Syngenta Seeds R&D Innovation Center in Illinois focuses also on improving crop yield and sustainability in North America through advanced genomics, automation and VR/AR. They enable large-scale testing including joint research with local farmers via provisioning high-throughput DNA sequencing, capability to support rapid pest resistance trials along with VR simulations to accelerate crop and hybrid development.

Besides, Switzerland´s Agroscope in partnership with the Swiss Food & Nutrition valley are driving change makers to sustainability agricultural practices and innovation on food technology at European level as well around the globe. Crop genetics, environmental sustainable projects, digital agriculture is what puts that all together for Switzerland farming development efforts. In Switzerland, Swiss Food & Nutrition Valley links early-stage ventures and academia in improving food quality, sustainability, and food production efficiency.

Last but not least, Impact Hub Istanbul and other EIT Food HUBs in eastern Europe offer a collaboration space for agriculture-impacting innovations to achieve the global SDGs in sustainable food production. They connect entrepreneurs with researchers or public sectors within training programs and digital transformation activities towards achieving sustainable agricultural practices by providing co-working spaces where cross-sectoral knowledge is shared.

## Contribution of Hubs and Experimentation centers

### Precision Agriculture and Digitalization 

All these entities contribute to innovation and technological developments, for example in digitalization and precision agriculture. Leading precision agriculture, hubs like SmartAgriHubs and DIH AGRIFOOD deploy big data along with advanced robotics as well as automated sensing technologies to provide agricultural end users with data-driven advice for improved optimization of farm variables including soil properties, irrigation, and pest control. FAO hubs also cater directly to sociotechnical specialists working in regions where little technological progress has been made; thereby making access by stakeholders at a broader scale, including youth and women. Swiss Food & Nutrition Valley contribute also to research advancements by generating knowledge on precision farming practices aiding connect local producers into cutting-edge digital tools while giving an exemplar vision that translates food production into sustainability goals built around quality standards recommended globally.

### Product Development and Testing 

In terms of accelerated product development and testing, Syngenta´s R&D Innovation Center, SouthEast Innovation Institute (SEII) support advanced genomics, pest resistance testing, automation, fast-track innovation cycles of new hybrid seeds and pest control solutions. SmartAgriHubs and DIH AGRIFOOD provide competence centers that host necessary environment testings where solutions can be customized and tested before wide-scale deployment thereby cutting down significantly on time needed for innovations delivery. Switzerland’s Agroscope plays vital role in providing experimental space to test sustainable agricultural practices as well as creating climate-resilient and environment friendly innovations.

### Capacity Building and Knowledge

Regarding capacity building and knowledge transfer, many hubs, notably FAO and DIH AGRIFOOD highlight the importance of capacity building and knowledge transfer by providing farmer, SMEs or other actors with training and mentorship, essential to upskill them. EIT Food HUBs and Impact Hub Istanbul have a similar function as collaborative ecosystems that connect research with entrepreneurship and digital agriculture leading to information transfer across borders. Lastly, Swiss Food & Nutrition Valley promotes knowledge-sharing via linking startups together with academic researchers and industry experts enabling local innovators in developing transformative solutions for scaling impact in the farming sector.

### Enhancements in Productivity and Sustainability

These innovative and technological advancements affect the agricultural ecosystem in many different ways. They increase competitiveness and efficiency, aided by advanced digital solutions and experimentation. These hubs are addressing enhancements in productivity. FAO hubs, for instance, pursue mainstreaming digital tools in agriculture, leading to gains in crop yields, and reduced waste of resources, while better managing climate risks. Additional sustainability productivity beyond crop yields also includes livestock management, soil health and water-use answering increased global demand on sustainable food production.  Swiss hubs especially activities derived from Agroscope are complement by conducting field research, strengthening productivity and sustainability of Swiss agriculture as well as competitiveness in the region’s agri-food sector.

### Sustainability and Climate Resilience

These developments in the agriculture also foster sustainability and climate resilience. On the sustainability front, initiatives such as SmartAgriHubs 4th Industrial Revolution demonstration projects provide climate-smart solutions to address pressing challenges like climate change, drought or pest resilience. Controlled-environment innovations at CHAP IHCEA (UK) and SEII (Southeast Asia) further support integrated approaches by testing water-efficient farming practices, resilient crop varieties and reduced reliance on chemical pesticide usage cross-border. Agroscope’s research focus in Switzerland has a focus towards preparing farms with robust-climate-smart agricultural options that will boost soil health, biodiversity and increase water conservation leading to a more-resilient agri-food ecosystem.

### Regional Development and Economic Diversification

Besides, with these advancements, regions are also developed and diversified by creating local innovation ecosystems, hubs such as DIH AGRIFOOD or the Global Network of FAO also help to drive regional economies forward, creating jobs in rural areas while providing opportunities for economic diversification within agriculture. Supporting agricultural innovations are especially essential when it comes to involving youth and women; not only to contribute to inclusive economic development but also to bring new perspectives in agriculture. Swiss Food & Nutrition Valley enables also collaboration between communities across Switzerland through sharing knowledge and talent; fostering a mindset that steers towards collaborative research projects, that promote regional innovation and economic diversification.

### Market Entry and Adoption of Innovations

Finally, these developments also facilitate market entry and adoption. The DIH one-stop-shop model by SmartAgriHubs aspires to improve the go-to-market pathway for digital solutions, driving low costs solution adoption by SMEs . This setup of ecosystem network ensures quicker adoption rates, and helps bring new technologies into more farms, with financial assistance from these hubs. This encourages large-and small-scale technology acceptance. Swiss Food & Nutrition Valley connects local food tech startups with investors and international markets that serve as a bridge to easier market access ensuring wider reach for innovative sustainable agricultural solutions.

To conclude, innovation hubs and experimentation centers in the agriculture ecosystem are indispensable for creating this digital transformation in agriculture. These hubs are working to provide practical tools for productivity and create inclusive ecosystems toward regionality, economy and sustainability that together can lead us into a collaborative future for agriculture. Digitalization, knowledge transfer and climate resilience are fundamental for a more resilient, productive and sustainable agri-food sector globally. All these entities around the world are having an impact on today's urgent food security challenges by innovating and encouraging cross-sector collaboration.

# Organizing for Innovation

## Organizational structures of agricultural businesses: 

In the agricultural sector, leading companies adopt a variety of organizational structures to drive innovation and maintain competitive advantage. These structures range from centralized R&D models to regional customer-focused frameworks, each designed to improve collaboration, streamline development processes or respond to local market needs. DHL's organizational strategies, presented by the speaker, offer further insights into the impact of different models on innovation. Here we will present some of these structures:

### Centralized R&D models

**Bayer CropScience and Syngenta AG**:

Bayer CropScience and Syngenta AG, for example, use centralized R&D structures to manage and coordinate their innovation efforts. This approach allows R&D activities to be consolidated within a centralized framework, enabling these companies to maintain strict oversight, align strategic objectives and efficiently allocate resources between projects. As DHL's approach shows, central supervision allows these companies to maintain consistency and control, which is invaluable in highly regulated sectors such as agriculture.

### Matrix structures 

**BASF SE and DowDuPont Inc**:

BASF and DowDuPont use a matrix organizational structure, combining functional and project teams. This model encourages cross-functional collaboration by allowing R&D, marketing and regulatory teams to work closely together on innovation projects. The matrix structure fosters an environment where ideas flow between departments, promoting innovation that is aligned with both technical advances and market needs, offering the company great agility to adapt. However, as DHL's experience shows, managing a matrix structure requires clear guidelines to avoid inefficiencies and wasting money in order to maintain project focus, as it is easy in this kind of structure for difficulties to arise when it comes to coordinating and agreeing between the different parties.

### Product-centered hierarchies 

**John Deere and CNH Industrial**:

John Deere and CNH Industrial operate with product-centric hierarchies, structuring their teams around specific machine categories. This model emphasizes specialist engineering and in-depth expertise within product lines, supporting targeted innovation in areas such as precision farming and autonomous machinery. DHL's ‘funnel’ approach to selecting and developing new technologies reflects this structure, as both models focus on selecting projects based on their potential impact and practicality, ensuring that resources are directed towards high-priority innovations.

### Customer-focused regional models 

**AGCO Corporation and Kubota Corporation**:

AGCO and Kubota use regional customer-centric models, which give autonomy to regional divisions to adapt products to local markets. This approach allows these companies to adapt their innovations to the specific needs of geographical areas and customers, making them agile in meeting diverse agricultural demands. DHL's digitization strategy, which adapts technology deployments to regional contexts, aligns with AGCO and Kubota's approach, demonstrating the value of adaptability and local customization within a broader strategic framework.

## Impact of organizational structures

Now let's talk about **the impact of these organizational structures on processes and outcomes**

The organizational structures adopted by these agricultural companies have a direct impact on their innovation processes and results, as they determine the way resources are managed, the way teams interact and the speed and efficiency with which companies can respond to market changes.

Bayer's and Syngenta's centralized R&D models create environments where innovation is highly coherent, standardized and aligned with regulatory standards. This structure favors a data-driven approach, enabling systematic product development and improvement in crop protection and biotechnology for example. However, centralization can slow response times to market developments, as decision-making is concentrated at higher levels. Despite this, the coherent framework enables reliable, regulatory-compliant innovation, strengthening their leadership in highly controlled product segments, which is the case in agriculture.

For the matrix structures of BASF and DowDuPont, these structures encourage the exchange of cross-functional knowledge, enabling different teams to contribute simultaneously to the innovation process. By integrating the expertise of different departments, these companies can accelerate development cycles and align new products with technical and market requirements. While the matrix model encourages adaptability and responsiveness, it also introduces management complexity. Structured project management practices within these companies help to mitigate potential inefficiencies and accelerate the time-to-market for solutions such as crop nutrition and pest control.

The product-focused hierarchies of John Deere and CNH Industrial enable highly targeted innovation in specific machine categories. This structure favors in-depth specialization and precision, particularly useful for developing high-performance, reliable equipment for precision farming. Although less flexible than other models, the product-centered approach enables these companies to produce robust, specialized machines that meet specific agricultural needs, which is very important in this industry. The structured, step-by-step scaling process, similar to DHL's pilot testing approach, ensures that each innovation is thoroughly tested and refined before being rolled out more widely.

AGCO's and Kubota's regional models, meanwhile, encourage localized innovation, enabling the development of solutions tailored to specific market conditions and customer preferences. This decentralized structure improves flexibility, as regional divisions can quickly adapt products to meet different farming challenges. However, decentralization requires effective coordination to maintain brand consistency and strategic alignment. The model fosters a strong culture of customer-focused innovation, supporting the development of compact machines that can be adapted to regional needs.

In conclusion, the different organizational structures of the major agricultural companies demonstrate the strategic balance between centralization and flexibility in the conduct of innovation. The centralized R&D models of Bayer and Syngenta guarantee consistency and reliability, while the matrix structures of BASF and DowDuPont encourage collaborative innovation that responds to market demands. The product-centric hierarchies of John Deere and CNH Industrial support the development of specialist, high-quality machinery, while the regional models of AGCO and Kubota enable locally relevant, customer-focused solutions. DHL's knowledge of structured scale and regional adaptability shows how agricultural businesses can optimize their organizational models to improve the reach and relevance of their innovations. Each structure offers unique advantages in meeting the challenges of global agriculture, with the choice of model influencing not only the speed and direction of innovation, but also the degree of market responsiveness. Thanks to these various organizational strategies, agricultural businesses are able to maintain a competitive edge and respond effectively to the changing needs of the agricultural ecosystem.

# Platforms and Ecosystems

## Introduction: Defining Platforms and Network Effects

In the context of business, platforms are intermediaries within the context of a given ecosystem, physical or digital, that allows disparate users to exchange tools, transaction and information. For instance, in agriculture, platforms are integrating farmers, suppliers, consumers, advisors, and financial services to improve processes, decrease inefficiencies, and foster innovation. In agriculture, platforms are key to connecting smallholder farmers to bigger markets, finance, new technologies, and sustainability.

Network effects are when the value of a platform increases the more users use and engage with it. For agriculture, network effects can enable platform growth and innovation by bringing in more farmers, consumers, and other stakeholders within industry, which can improve data collection, access to market and funding for all players. Network effects are a key source of a platform's success and relevance because platforms can benefit from accumulating rich data to customize their services, streamline operations, and stimulate agricultural innovation as they scale.

## Key Platforms Operating in the Agriculture Ecosystem (Worldwide)

Different agricultural platforms are transforming ecosystems around the world by tackling specific needs and challenges in their respective geographies. These are specific platforms in their respective continents. In Africa, there is two key platforms: **Hello Tractor**, which is a Nigerian “Uber for tractors” and **M-Farm** in Kenya, which is a digital marketplace and information-sharing platform. In Europe, **ATLAS** platform fosters data interoperability in agriculture and **DEMETER** establishes an Agricultural Interoperability Space. Besides, in North America, **Farmers Business Network** in the US provides input procurement, agronomic data and market information for farmers in comparison to **Indigo Agriculture**, which is an American marketplace rewarding for regenerative practices adoption. On the other hand, in South America, in Brazil, **Agrosmart** provides IoT-based climate and crop monitoring systems. Finally, in Asia, the Chinese e-commerce platform, **Pinduoduo**, allows consumers to buy directly from the farm and enables farmers to have a more extensive market without intermediates and in India, **Ninjacart** is an online platform that directly connects farmers and retailers.

## How Platforms Facilitate Interactions Among Ecosystem Participants

### Collaboration and Knowledge Sharing

By allowing farmers to exchange information, often allowing them to obtain aggregated data, platforms like Hello Tractor and Farmers Business Network (FBN) create a shared ecosystem around learning and innovation.

Take *Hello Tractor*, for example, which connects tractor owners with smallholder farmers who require access to affordable tractor services but cannot afford to own the machinery themselves. It provides an on-demand booking of tractor services for farmers, and the data collected on tractor usage ensures that owners maximize asset utilization. Moreover, *Hello Tractor* acquires and analyzes usage data to provide insights into regional agricultural trends and to inform farmers of the best crop practices and resource allocations.

In a similar manner, *Farmers Business Network* (FBN) gives farmers a way to share knowledge on the platform and get recommendations that come from combining data from thousands of farms across multiple regions. FBN enables farmers to make more informed decisions regarding risk management and price negotiation through the collection of market prices, input costs, and agronomic information. Moreover, the data-driven nature of FBN promotes transparency and trust among farmers while allowing them to adjust to market dynamics and adopt best practices.

In both cases these platforms are channels of information and knowledge, where farmers are optimizing their practice from shared experience and data-driven insights. Ultimately, by fostering collaboration, these platforms will be key to a more resilient and more informed agricultural community ready to face challenges together.

### Supply Chain Efficiency and Market Access

Some of the biggest challenges in agriculture are supply chain inefficiencies and lack of market access, and platforms such as *Pinduoduo* in China and *Ninjacart* in India solve these problems directly by linking farmers to consumers or retailers. These e-commerce platforms not only cut out the middlemen in the supply chain but also make sure that the entire profit does not go to the intermediaries and farmers earn a better share of the profit.

*Pinduoduo* is a very large Chinese e-commerce platform that has engaged with rural farmers and connecting them directly to urban consumers with online fresh produce marketplace. *Pinduoduo* drives demand for agricultural products and provides many small farmers with access to a large market without intermediaries, thanks to its social commerce model where buyers can come together to buy at discount prices. By doing so, it increases the income of farmers and makes fresh products with lower prices available and accessible to urban consumers, creating a win-win situation.

In the same way, *Ninjacart* in India is linking farmers and retailers also using a technology-defined supply chain for an efficient logistics and reducing food wastage. *Ninjacart* reduces the time taken for transporting produce from farms to urban centers and preserves freshness and minimize losses by using data analytics for demand forecasting and delivery route optimization. It also guarantees that farmers get paid promptly, relieving the cash flow problems that smallholder farmers regularly experience. These platforms such as *Ninjacart* streamline supply chain management that profits small farmers but also ensure competitive and fresher products to the consumers.

### Financial and Advisory Services

For farmers who want to invest in new technology or scale their operations, access to financial and advisory services is crucial, but traditional financial institutions tend to consider agribusiness as high risk. This is where platforms such as *M-Farm* in Kenya and *Indigo Agriculture* in the USA come in. They provide customized financial products and advisory services that provide farmers with the ability to hedge against risks and be more empowered in making decisions.

In Kenya, for instance, *M-Farm* is a digital marketplace that provides farmers with real-time market prices and direct access to buyers, and offers key information that farmers can use to negotiate better deals. *M-Farm* also plays a role in giving farmers access to credit and insurance services tailored to their agricultural requirements. *M-Farm* uses data from farmers, such as sales and transaction data, with the aim of evaluating creditworthiness and offer financial products to farmers at lower rates than traditional lenders, allowing farmers to access high-quality inputs or expansion with ease.

*Indigo Agriculture* provides farmers with a platform to access carbon credits and regenerative agriculture practices to help drive regenerative agricultural practices in the USA. Instead of merely preventing farmers from contributing to the problem, earning carbon credits allow farmers to earn money for participating in sustainable practices, such as cover cropping or reduced tillage, that encourage meaningful reductions in greenhouse gas emissions. This gives farmers a secondary revenue stream and encourages environmentally sustainable practices. In addition, *Indigo's* advisory services enable farmers to overcome the difficulties of carbon farming, such as compliance and monitoring requirements, making sustainability easier and more profitable.

## Assessing the Impact of Network Effects on Innovation

### Enhanced Data Collection and Analytics

*Agrosmart* in Brazil and *DEMETER* in Europe demonstrate network effects increasing the data collected, which results in higher-quality analytics and insights for the users. Agrosmart collects real-time data from farms through IoT sensors to measure climate conditions, soil moisture and crops health. With additional farmers using the platform, *Agrosmart* aggregates this data to create more accurate local climate models and forecast pest outbreaks and produce localized management recommendations to farmers based on climate conditions. This type of predictive analytics enables data-driven decision-making on the farmers' part, for example, to alter their irrigation schedule, or to apply pesticides only when absolutely necessary, ultimately saving time and costs, in addition to preserving resources.

Likewise, *DEMETER* combines data from different sources: sensors, drones, and satellite images from space, to give farmers information about the yield of their products, the market demand, and environmental factors. The dataset of the platform can keep expanding as the platform grows, which increases the accuracy of recommendations given by the platform. It also gives *DEMETER* the ability to assist agricultural research by using data to identify trends, utilize resources to their full potential and enhance productivity. Through advanced analytics, *Agrosmart* and *DEMETER* enable farmers to more effective practices that will help them to boost and become more sustainable.

### Accelerated Technology Adoption

These network effects are also key to accelerating adoption of advanced farming technology and sustainable practices. *Indigo Agriculture* in the US and *ATLAS* in Europe have demonstrated the capacity to scale use of IOT devices, machine learning and regenerative agriculture techniques by literally showing farmers how to benefit from what they do.

*Indigo Agriculture* pays farmers to adopt regenerative practices. This leads to a virtuous cycle, more farmers join *Indigo*, which makes a carbon credit more credible and with a higher market value, which attracts more farmers

*ATLAS* provides an open interoperability network for smart farming applications in Europe. With the interlink of different IoT devices, sensors, and data analytic tools, *ATLAS* helps farmers to use precision agriculture techniques that are highly based on their needs. By publishing success stories and letting farmers participating in a network of peer support, *ATLAS* makes it easy for hesitant farmers to transition into data-driven farming as more and more farmers adopt these tools. By demonstrating how technology works, supported by increasing user base, the platform fastens the scientific innovations adoption across the agricultural community.

### Creation of Complementary Innovations

As they scale, platforms pull in third-party developers and service providers who together build complementary innovations that enhance the core capabilities of the platform. This allows an ecosystem effect to happen, where products and services are growing around the platform, enriching users' experiences and extending the capabilities of the platform.

For example, through its Agriculture Interoperability Space (AIS) and Agriculture Information Model (AIM), *DEMETER* support interoperability by allowing third-parties to build applications which can seamlessly integrate with existing agricultural tools. This interoperability can be leveraged by the third-party developers to build applications such as pest management or precision irrigation tools or even crop disease detection systems based on the existing *DEMETER* data. *DEMETER* creates more value proposition for farmers. This means, with *DEMETER* farmers will gain access to better tools, hopefully catering to different types of farming needs. This helps end users, i.e. farmers, but also creates business opportunities for software providers, hardware suppliers and advisory services in the agricultural sector.

In a similar way, *M-Farm* in Kenya has gone beyond being a marketplace for farmers into new services (microloans, insurance, and advisory tools) targeting smallholder farmers. This has allowed third parties to create supporting innovations around *M-Farm* so that it can evolve from just a platform to an ecosystem that supports all stages of the farming lifecycle, from seed purchase to market sale.

Platforms also have the ability to provide a one-stop-shop experience for farmers through complementary innovations; offering a large set of tools and services designed to address a number of agricultural challenges. It creates an ecosystem which enables continual innovation, keeping platforms responsive and relevant to the changing needs of the agricultural sector.

### Challenges of Dominant Platforms

Network effects may be the driving force that powers growth and innovation, but they have the disadvantage of leading to platform monopolization. Under this process, several problems can be observed, such as limited competition, limited diversity in innovation and higher dependence on the leading platform itself.

By way of example in China, one of the largest agricultural e-commerce platforms, *Pinduoduo*, At the same time, its dominant position leads to worry about monopolistic control. Farmers overly dependent on *Pinduoduo* could be in an awkward position to bargain or to access other markets. In the long run, the monopoly of the platform might discourage new entrants, which means less competition, or even lower innovation within in the industry sector. Farmers might become less and less autonomous as prices and market access fall under the monopoly control of the platform, which would also make them subject to the platform policies and algorithms.

Likewise, in areas where platforms such as *Farmers Business Network* (FBN) dominate, the threat exists that farmers would have reduced options in input suppliers and data analytics providers. As a leading provider of data-driven insights to the farmer community, FBN’s stronghold may make it difficult for other solutions to gain traction, limiting the diversity of tools and perspectives available to farmers. FBN has made the information most farmers need more readily accessible to a wider range of people, but its dominance could eventually impact competition, limiting farmer’s options and innovation.

In response to these challenges, regulators and policymakers will need to set guidelines for data portability, interoperability and fair competition on agricultural platforms. While network effects can create tremendous benefits for an ecosystem, we should encourage open standards and support multiple ecosystems so that the benefits of the network effects do not come at the expense of competition and innovation diversity.

# Intellectual Property Strategy

## IP Strategies and their impact on innovation 

The Agrifood sector is a major segment of the innovation system with over 3.5 million patent families published in the last 20 years.  Agrifood is divided into two main categories: AgriTech and FoodTech. It turns out the AgriTech sub-domain contributes to the vast majority of patent families, at 60%, compared to 40% patent families for FoodTech. There is a strong patent concentration throughout this field among Asia. In the overall Agrifood domain, 78% patent families are non-international and based in Asia, while only 12% registered as international patents. Within AgriTech, this trend is even stronger with 85% of patents held by Asian actors being identified as non-international, versus 14% as international. Likewise, for FoodTech 79% of patents remain in Asia, with only 10% being international. These numbers indicate a regional concentration in Agrifood patents, with limited cross-border sharing of intellectual property. Mapping the strategic context in Agrifood, AgriTech and FoodTech with an understanding of the patent landscape and intellectual property strategies is essential for analyzing how key patents and IP holdings shape collaboration and competition within this ecosystem.

# #IMAGES

## Key Patents and IP Holdings in Agricultural Technology

### Soil and Fertilizer Management

Global machinery manufacturers and chemical companies have a strong presence in this sector, with top players including Deere, CNH Industrial, Kubota, BASF, and Bayer holding the majority of patents. Deere has a diversified portfolio of patents for devices for agriculture including tractors and devices for automated soil management. When it comes to fertilizer formulation and biocides, the leadership is German by companies like BASF and Bayer, with strong IP portfolio in soil health and crop growth. The IP approaches here center on the protection of innovations across regions with two large scale economy areas, Europe and the United States, where the regulatory landscape is strict and competition is fierce.

# #GRAPH

### Non-Pesticide Pest and Disease Management

This category is led by agrochemical giants, with BASF and Bayer as leaders. The solutions include innovations like pheromone-based pest control and allelochemical formulations that are available in their Biocontrol portfolio. Asian firms like Shin-Etsu Chemical and Sumitomo Chemical also have patents for inventive ways to control pests. Furthermore, the patent based IP strategies cover developed as well as emerging markets. These companies' patent holdings serve not only to protect the innovation, but they also serve as a barrier to entry for small players, which in turn strengthens the company's control of the market.

# #GRAPH

### Alternative Nutrient Sources for Human Food

Top companies such as Pioneer Hi-Bred International, Nestlé and DSM-Firmenich have patents on plant-, insect- and algae-derived proteins in this area. Their portfolios range from nutrient extraction to processing to formulation. For instance, Nestlé has patents solely on certain protein extraction and purification methods. The strategic use of IP in this category supports product differentiation and expands the market for alternative proteins We can observe both collaborations and acquisitions in this category as traditional meat and dairy companies make moves to monopolize their IP holdings to diversify their portfolios (I.e. Tyson Foods and General Mills entering the plant-based segment).

# #GRAPH

### Predictive Models in Precision Agriculture

It is an industrial player segment where Deere, BASF, and Bayer are all leading the way. Their intellectual property portfolio encompasses predictive models of crop and soil state, while Bayer is focusing on soil analysis and yield prediction through machine learning approaches. American tech giants such as IBM and Alphabet have also filed patents in this area, particularly about IoT ecosystems and machine learning for agriculture. The IP strategy here emphasizes innovation in data-driven agriculture, with patents protecting proprietary algorithms and machine learning models. It enables companies to leverage data-driven insights, strengthening their competitive advantage.

# #GRAPH

### Autonomous Devices in Precision Agriculture

This segment is partly fed by companies such as Deere, CLAAS and Kubota, developing self-steering tractors and robotic harvesters. Deere tops patenting featuring rights covering automated harvesters, while German firms like CLAAS and Amazonen-Werke focus on autonomous sprayers and fertilizer spreaders. It is important for IP strategies to secure automation and robotics advancements, which are crucial to scaling and efficiency of modern agriculture. This enables companies to gain large market shares because these automations can rarely be copied quickly, thus helping keep these firms as long-term market leaders in automation.

# #GRAPH

## Influence of IP Strategies on Collaboration and Competition

### Competitive Barriers and Market Leadership

The IP strategies in agricultural technology rise significant competitive barriers. In fact, for companies like Deere, which holds significant amounts of IP around predictive models as well as autonomous machinery, that position them as market leader, with patents preventing competitors from easily replicating their technology. The dominance of BASF and Bayer over soil management and pest control patents restricts smaller firms to enter these segments too. These firms can expand their own market shares, deepen their industry leadership and raise the barriers against other firms by monopolizing essential patents.

### Strategic Collaborations and Knowledge Sharing

IP protection not only limits competition but also encourages strategic partnerships. Behind Nestlé and DSM-Firmenich in the Alternative Nutrient Sources category are other companies that are partnering with startups and research institutions to develop the next generation of sustainable food technologies. Through patents licensing and joint ventures, these firms increase their innovative capabilities while absorbing knowhow from outside partners. Precision agriculture has also seen a similar play with AgriTech companies partnering with technology giants like IBM to create significant joint IP that deliver advanced AI capabilities that brings agriculture into the future. This approach enhances innovation by combining strengths from different fields while still protecting proprietary technologies.

### Regional and Sectoral Expansion

IP strategies empowers companies to grow regionally and sector wise. Japanese companies such as Kubota and Honda have patents largely in Asia, but also in Europe and the United States. By being able to be located anywhere, they can pursue new geographical markets while leveraging existing innovation. Within Non-Pesticide Pest and Disease Management sector, firms such as Sumitomo Chemical and Shin-Etsu utilize their patents to establish market access in new geographical areas, customizing their biocontrol technologies to regional regulatory requirements and ecological demands. These regional IP strategies contribute to internationalization and sectoral diversification, increasing the impact and reach of agricultural innovations.

### Impact on Innovation Ecosystem and Collaboration Models

This IP holdings trend of industrial players against academic institutions impacts the innovation ecosystem. Universities end up with so little IP in areas such as Soil and Fertilizer Management due to this practice that it actually hinders the open sourcing of knowledge. That can suppress collaborative, every-day innovation because industrial IP control limits access to basic technologies. In contrast, Cargill and Nestlé will have their IP in alternative proteins but follow an open innovation model by licensing their IP to smaller firms and startups, establishing a powerful coopetition framework that promotes even more innovation in the ecosystem. This combination of competition and collaboration creates an innovation ecosystem that fosters proprietary knowledge protection coupled with selective sharing to promote growth.

The patent strategies of the top agricultural technology firms reveals a mix of competition and cooperation. As firms have locked critical patents in Soil and Fertilizer Management, Pest Control, Alternative Nutrients, Predictive Models and Autonomous Devices, they maintain their competitive advantage, with high barriers for new entrants. This fortifies international reach, drives partnerships, and powers the innovation landscape in the agriculture ecosystem. Intellectual property protection can restrict open innovation in monopolized sectors, but sharing with licenses and partnerships enables all to grow together. Finally, these are the IP strategies that empower firms to use innovation for the long-term competitive advantage of the company which in turn design the landscape of sustainable and efficient agriculture of the future.

### 
